ghost_rules:
  need_permission2play: true
  response_timeout: 3      # 秒
  valid_response_min_length: 1
  ignore_bot_mentions: true   # 是否忽略 bot 間的 mention

commands:
  ghost:
    enable: true
  reset:
    enable: false
  rank:
    enable: true
    # display_default_limit: 10
    # disaply_max_limit: 50
  config:
    enable: true
  join:
    enable: true
  quit:
    enable: true

events:
  on_ready:
    enable: true
  on_message:
    enable: true
  on_voice_state:
    enable: false


# 資料庫設定
database:
  type: "sqlite"
  path: "database/ghost_rank.sqlite"